# Copyright (c) 2023-2026, HaiyangLi <quantocean.li at gmail dot com>
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from lionagi.service.connections.endpoint import Endpoint

from ._config import OpenAIConfigs


class OpenAIBatchOutputExpiration(BaseModel):
    """Expiration policy for files generated by an OpenAI batch."""

    model_config = ConfigDict(extra="forbid")

    anchor: Literal["created_at"]
    seconds: int = Field(strict=True, ge=3600, le=2_592_000)


class OpenAIBatchRequest(BaseModel):
    """Request body for creating an OpenAI batch."""

    input_file_id: str
    endpoint: Literal[
        "/v1/responses",
        "/v1/chat/completions",
        "/v1/embeddings",
        "/v1/completions",
        "/v1/moderations",
        "/v1/images/generations",
        "/v1/images/edits",
        "/v1/videos",
    ]
    completion_window: Literal["24h"]
    metadata: dict[str, str] | None = None
    output_expires_after: OpenAIBatchOutputExpiration | None = None


__all__ = (
    "OpenAIBatchOutputExpiration",
    "OpenAIBatchRequest",
    "OpenaiBatchEndpoint",
)


@OpenAIConfigs.BATCH.register
class OpenaiBatchEndpoint(Endpoint):
    """OpenAI batch creation endpoint."""
