import { act, type ReactNode } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const createdWorkflow = vi.hoisted(() => ({
  id: "wf_01JZ9K8Y5M",
  name: "Réview flow: alpha/beta?",
  created_at: 42,
}));

const router = vi.hoisted(() => ({
  search: {} as Record<string, string | undefined>,
  navigate: vi.fn(),
}));

const api = vi.hoisted(() => ({
  listAgents: vi.fn(),
  listWorkflowDefs: vi.fn(),
  listSkills: vi.fn(),
  listPlugins: vi.fn(),
  listEngineDefs: vi.fn(),
  listBuiltinPlaybooks: vi.fn(),
  listPlaybooks: vi.fn(),
  listMcpServers: vi.fn(),
}));

vi.mock("@tanstack/react-router", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@tanstack/react-router")>();
  return {
    ...actual,
    createFileRoute: () => (options: Record<string, unknown>) => ({
      ...options,
      useSearch: () => router.search,
    }),
    useNavigate: () => router.navigate,
    Link: ({ children }: { children: ReactNode }) => children,
  };
});

vi.mock("use-intl", () => ({
  useTranslations: () => (key: string) => key,
}));

vi.mock("@/lib/api", () => api);

vi.mock("@/components/ui/SplitPane", () => ({
  default: ({ master, detail }: { master: ReactNode; detail: ReactNode }) => (
    <>
      {master}
      {detail}
    </>
  ),
}));

vi.mock("@/components/library/WorkflowDetail", () => ({
  CreateWorkflowPanel: ({
    onCreated,
  }: {
    onCreated: (workflow: typeof createdWorkflow) => void;
  }) => (
    <button type="button" data-testid="complete-create" onClick={() => onCreated(createdWorkflow)}>
      complete create
    </button>
  ),
  WorkflowDetail: ({ id }: { id: string }) => (
    <div data-testid="workflow-detail" data-workflow-id={id} />
  ),
}));

vi.mock("@/components/library/AgentDetail", () => ({ AgentDetail: () => null }));
vi.mock("@/components/library/CreateAgentPanel", () => ({ CreateAgentPanel: () => null }));
vi.mock("@/components/library/PlaybookTemplateDetail", () => ({
  PlaybookTemplateDetail: () => null,
}));
vi.mock("@/components/library/McpServerDetail", () => ({
  McpServerDetail: () => null,
  CreateMcpServerPanel: () => null,
}));
vi.mock("@/components/library/SkillDetail", () => ({ SkillDetail: () => null }));
vi.mock("@/components/library/PluginDetail", () => ({ PluginDetail: () => null }));

// TanStack Router's Vite plugin materializes this test-only split module; it
// has no source declaration for TypeScript to resolve.
// @ts-expect-error virtual module generated by @tanstack/router-plugin
const { component: LibraryPage } = await import("./library.tsx?tsr-split=component");

interface Deferred<T> {
  promise: Promise<T>;
  resolve: (value: T) => void;
  reject: (reason: unknown) => void;
}

function deferred<T>(): Deferred<T> {
  let resolve!: (value: T) => void;
  let reject!: (reason: unknown) => void;
  const promise = new Promise<T>((resolvePromise, rejectPromise) => {
    resolve = resolvePromise;
    reject = rejectPromise;
  });
  // A deferred a test rejects may never be consumed, so it swallows its own
  // rejection rather than surfacing as an unhandled one that fails the run.
  promise.catch(() => {});
  return { promise, resolve, reject };
}

async function flush() {
  await act(async () => {
    await Promise.resolve();
    await Promise.resolve();
    await Promise.resolve();
  });
}

// The workflow tab is in UNFINISHED_KINDS, so these drive the detail pane a
// workflow selection still renders rather than a tab row. Right after a create
// the optimistic id answers, so the catalog reload these set up is not always
// consumed; each deferred therefore owns a catch of its own.
describe("Library workflow creation identity", () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true);
    Object.values(api).forEach((mock) => mock.mockReset());
    router.search = {};
    router.navigate.mockReset();
    router.navigate.mockImplementation(
      ({
        search,
      }: {
        search: (previous: Record<string, string | undefined>) => typeof router.search;
      }) => {
        router.search = search(router.search);
        return Promise.resolve();
      },
    );

    api.listAgents.mockResolvedValue({ agents: [] });
    api.listBuiltinPlaybooks.mockResolvedValue({ playbooks: [] });
    api.listPlaybooks.mockResolvedValue({ playbooks: [] });
    api.listSkills.mockResolvedValue({ skills: [] });
    api.listPlugins.mockResolvedValue({ plugins: [] });
    api.listEngineDefs.mockResolvedValue([]);
    api.listMcpServers.mockResolvedValue({ servers: [] });

    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
    vi.unstubAllGlobals();
  });

  async function createWhileReloadIsPending(reload: Deferred<unknown[]>) {
    api.listWorkflowDefs.mockResolvedValueOnce([]).mockReturnValueOnce(reload.promise);

    await act(async () => {
      root.render(<LibraryPage />);
    });
    await flush();

    const newButton = [...container.querySelectorAll("button")].find((button) =>
      button.textContent?.includes("newWorkflow"),
    );
    expect(newButton).toBeDefined();
    await act(async () => newButton?.click());

    const completeButton = container.querySelector<HTMLButtonElement>(
      '[data-testid="complete-create"]',
    );
    expect(completeButton).not.toBeNull();
    await act(async () => completeButton?.click());
    await flush();
  }

  it("uses the returned id for detail while the catalog reload is delayed", async () => {
    const reload = deferred<unknown[]>();
    await createWhileReloadIsPending(reload);

    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);
    expect(
      container.querySelector<HTMLElement>('[data-testid="workflow-detail"]')?.dataset.workflowId,
    ).toBe(createdWorkflow.id);

    reload.resolve([
      {
        ...createdWorkflow,
        description: null,
        spec_json: null,
        updated_at: createdWorkflow.created_at,
      },
    ]);
    await flush();

    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);
    expect(
      container.querySelector<HTMLElement>('[data-testid="workflow-detail"]')?.dataset.workflowId,
    ).toBe(createdWorkflow.id);
  });

  it("keeps the returned id usable when the catalog reload fails", async () => {
    const reload = deferred<unknown[]>();
    await createWhileReloadIsPending(reload);

    reload.reject(new Error("catalog unavailable"));
    await flush();

    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);
    expect(
      container.querySelector<HTMLElement>('[data-testid="workflow-detail"]')?.dataset.workflowId,
    ).toBe(createdWorkflow.id);
  });

  it("resolves a workflow deep link with no create behind it", async () => {
    router.search = { sel: `workflow:${createdWorkflow.name}` };
    api.listWorkflowDefs.mockResolvedValue([
      { id: "wf_other", name: "something else" },
      { id: createdWorkflow.id, name: createdWorkflow.name },
    ]);

    await act(async () => {
      root.render(<LibraryPage />);
    });
    await flush();

    expect(api.listWorkflowDefs).toHaveBeenCalled();
    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);
    expect(
      container.querySelector<HTMLElement>('[data-testid="workflow-detail"]')?.dataset.workflowId,
    ).toBe(createdWorkflow.id);
  });

  it("holds a workflow link selected after the catalog has already loaded", async () => {
    // Selecting on a loaded catalog is the case the mount path cannot reach:
    // there, the resolve has already settled by the time the selection effect
    // stops being short-circuited by `loading`. Here both effects run in one
    // commit, and the selection effect reads the resolve state from before its
    // sibling set it, so requiring a positive pending discards the link.
    const inFlight = deferred<unknown[]>();
    // The catalog never requests workflows, so this mock answers only the
    // resolve effect; a `mockResolvedValueOnce` here would be eaten by it.
    api.listWorkflowDefs.mockReturnValue(inFlight.promise);

    router.search = {};
    await act(async () => {
      root.render(<LibraryPage />);
    });
    await flush();

    router.search = { sel: `workflow:${createdWorkflow.name}` };
    await act(async () => {
      root.render(<LibraryPage />);
    });
    await flush();

    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);

    inFlight.resolve([{ id: createdWorkflow.id, name: createdWorkflow.name }]);
    await flush();
    expect(router.search.sel).toBe(`workflow:${createdWorkflow.name}`);
  });

  it("drops a workflow deep link whose name no longer exists", async () => {
    router.search = { sel: "workflow:deleted" };
    api.listWorkflowDefs.mockResolvedValue([
      { id: createdWorkflow.id, name: createdWorkflow.name },
    ]);

    await act(async () => {
      root.render(<LibraryPage />);
    });
    await flush();

    expect(router.search.sel).not.toBe("workflow:deleted");
    expect(container.querySelector('[data-testid="workflow-detail"]')).toBeNull();
  });
});
