# Copyright (c) 2023-2026, HaiyangLi <quantocean.li at gmail dot com>
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import logging
from collections.abc import AsyncIterator, Callable
from typing import Any

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

__all__ = [
    "HandoffCondition",
    "AgentSpec",
    "GroupChatSpec",
    "ResearchPlan",
    "AG2GroupChatRequest",
    "build_group_chat",
    "stream_group_chat",
]


# ---------------------------------------------------------------------------
# Models (structured output targets)
# ---------------------------------------------------------------------------


class HandoffCondition(BaseModel):
    """When to hand off to another agent.

    Maps to AG2 v0.12::

        OnCondition(
            target=AgentTarget(target_agent),
            condition=StringLLMCondition(prompt=condition),
        )
    """

    target: str = Field(description="Target agent name to hand off to")
    condition: str = Field(
        description="Natural language condition for handoff trigger",
    )


class AgentSpec(BaseModel):
    """Specification for a single AG2 agent in a GroupChat.

    Maps to AG2 v0.12::

        agent = ConversableAgent(name, system_message, llm_config, ...)
        register_function(tool_fn, caller=agent, executor=user_proxy)
        agent.handoffs.add_llm_conditions([OnCondition(...)])
        # v0.12: update_agent_state_before_reply=[UpdateSystemMessage(...)]
    """

    name: str = Field(description="Agent name (e.g. 'Researcher', 'Analyst')")
    role: str = Field(description="One-line role description")
    system_message: str = Field(default="", description="Full system prompt for the agent")
    tools: list[str] = Field(
        default_factory=list,
        description="Tool names from the registry this agent can invoke",
    )
    handoffs: list[HandoffCondition] = Field(
        default_factory=list,
        description="Conditions for handing off to other agents",
    )
    nlip_url: str | None = Field(
        default=None,
        description="If set, this agent is a remote NLIP agent at the given URL. "
        "system_message and llm_config are ignored — the remote server handles them.",
    )
    state_template: str | None = Field(
        default=None,
        description=(
            "Dynamic system message template using context variables. "
            "Maps to AG2 v0.12 UpdateSystemMessage. "
            "Example: 'Insights stored: {insights_stored}'"
        ),
    )


class GroupChatSpec(BaseModel):
    """Specification for a single AG2 GroupChat — one node in a DAG."""

    name: str = Field(description="GroupChat identifier")
    objective: str = Field(description="What this GroupChat should accomplish")
    agents: list[AgentSpec] = Field(description="Participating agents")
    max_round: int = Field(default=15, gt=0, description="Maximum conversation rounds")
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Initial context variables shared across agents",
    )


class ResearchPlan(BaseModel):
    """Full research plan generated by LLM via structured output."""

    topic: str = Field(description="The research topic")
    hypothesis: str = Field(description="Central hypothesis to test")
    group_chats: list[GroupChatSpec] = Field(
        description="Independent GroupChat teams running in parallel",
    )
    synthesis_instruction: str = Field(
        description="How to combine all GroupChat outputs",
    )
    expected_output: str = Field(
        description="What the final deliverable should look like",
    )
    safeguard_policy: list[str] = Field(
        default_factory=list,
        description="Research governance guidelines enforced at conversation level",
    )


class AG2GroupChatRequest(BaseModel):
    """Request for AG2 GroupChat endpoint."""

    messages: list[dict[str, Any]] = Field(default_factory=list)
    prompt: str = ""
    max_round: int = Field(default=15, gt=0)
    context_variables: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Callback types (parallel to claude_code.py on_* handlers)
# ---------------------------------------------------------------------------

AG2_HANDLER_PARAMS = (
    "on_text",
    "on_tool_use",
    "on_tool_result",
    "on_speaker",
    "on_complete",
)


# ---------------------------------------------------------------------------
# Runner (in-process — no subprocess, unlike claude_code.py)
# ---------------------------------------------------------------------------


def build_group_chat(
    spec: GroupChatSpec,
    llm_config: Any,
    tool_registry: dict[str, Callable] | None = None,
    code_executor: Any | None = None,
):
    """Build AG2 agents and DefaultPattern from a GroupChatSpec.

    Returns (user_proxy, pattern, agents_by_name).
    """
    from autogen import ConversableAgent, register_function
    from autogen.agentchat.conversable_agent import UpdateSystemMessage
    from autogen.agentchat.group import (
        AgentTarget,
        ContextVariables,
        OnCondition,
        StringLLMCondition,
        TerminateTarget,
    )
    from autogen.agentchat.group.patterns import DefaultPattern

    tool_registry = tool_registry or {}
    user_configs = {
        "name": "User",
        "human_input_mode": "NEVER",
        "llm_config": False,
    }
    if code_executor:
        user_configs["code_execution_config"] = {"executor": code_executor}

    user = ConversableAgent(**user_configs)

    agents_by_name: dict[str, ConversableAgent] = {}
    ordered: list[ConversableAgent] = []

    for agent_spec in spec.agents:
        if agent_spec.nlip_url:
            # SSRF guard: validate the caller-supplied URL before handing it
            # to NlipRemoteAgent, which opens its own HTTP connection and
            # bypasses the Endpoint transport guards.
            from lionagi.providers.ag2.nlip.models import _assert_nlip_url_safe

            _assert_nlip_url_safe(agent_spec.nlip_url)
            try:
                from autogen.agentchat.contrib.nlip_agent import NlipRemoteAgent

                agent = NlipRemoteAgent(
                    url=agent_spec.nlip_url,
                    name=agent_spec.name,
                )
            except ImportError:
                logger.warning(
                    "nlip_sdk not installed — creating %r as local agent instead",
                    agent_spec.name,
                )
                agent = ConversableAgent(
                    name=agent_spec.name,
                    system_message=agent_spec.system_message or f"You are {agent_spec.name}.",
                    llm_config=llm_config,
                    human_input_mode="NEVER",
                )
        else:
            kwargs: dict[str, Any] = dict(
                name=agent_spec.name,
                system_message=agent_spec.system_message,
                llm_config=llm_config,
                human_input_mode="NEVER",
            )
            if agent_spec.state_template:
                kwargs["update_agent_state_before_reply"] = [
                    UpdateSystemMessage(agent_spec.state_template),
                ]

            agent = ConversableAgent(**kwargs)

            for tool_name in agent_spec.tools:
                if tool_name in tool_registry:
                    fn = tool_registry[tool_name]
                    desc = getattr(fn, "__doc__", "") or tool_name
                    register_function(
                        fn,
                        caller=agent,
                        executor=user,
                        description=desc,
                    )

        agents_by_name[agent_spec.name] = agent
        ordered.append(agent)

    for idx, agent_spec in enumerate(spec.agents):
        agent = agents_by_name[agent_spec.name]
        for hc in agent_spec.handoffs:
            if hc.target in agents_by_name:
                agent.handoffs.add_llm_conditions(
                    [
                        OnCondition(
                            target=AgentTarget(agents_by_name[hc.target]),
                            condition=StringLLMCondition(prompt=hc.condition),
                        )
                    ]
                )
            else:
                logger.warning(
                    "Handoff target %r from agent %r not found in spec — skipped",
                    hc.target,
                    agent_spec.name,
                )

        # Mechanical fallback: each non-terminal agent flows to the next agent
        # in spec order if no LLM-condition handoff fires.  This guarantees the
        # pipeline reaches the terminal agent rather than ending early when the
        # group manager's auto-select picks User (terminate).
        if idx < len(spec.agents) - 1:
            next_agent = agents_by_name[spec.agents[idx + 1].name]
            agent.handoffs.set_after_work(AgentTarget(next_agent))

    if ordered:
        ordered[-1].handoffs.set_after_work(TerminateTarget())

    pattern = DefaultPattern(
        initial_agent=ordered[0] if ordered else user,
        agents=ordered,
        user_agent=user,
        context_variables=ContextVariables(data=spec.context),
    )

    return user, pattern, agents_by_name


async def stream_group_chat(
    pattern,
    prompt: str,
    max_rounds: int = 15,
    safeguard_policy: dict[str, Any] | None = None,
    yield_on: list | None = None,
    on_text: Callable[[str, str], None] | None = None,
    on_tool_use: Callable[[str, str, Any], None] | None = None,
    on_tool_result: Callable[[str, Any], None] | None = None,
    on_speaker: Callable[[str], None] | None = None,
    on_complete: Callable[[Any], None] | None = None,
) -> AsyncIterator[Any]:
    """Stream AG2 GroupChat events. In-process, no subprocess.

    Yields AG2 BaseEvent objects. Optionally calls on_* handlers.
    """
    from autogen.agentchat.group.multi_agent_chat import a_run_group_chat_iter
    from autogen.events.agent_events import (
        GroupChatRunChatEvent,
        SelectSpeakerEvent,
        TextEvent,
        ToolCallEvent,
        ToolResponseEvent,
    )

    if yield_on is None:
        yield_on = [
            TextEvent,
            ToolCallEvent,
            ToolResponseEvent,
            SelectSpeakerEvent,
            GroupChatRunChatEvent,
        ]

    kwargs: dict[str, Any] = dict(
        pattern=pattern,
        messages=prompt,
        max_rounds=max_rounds,
        yield_on=yield_on,
    )
    if safeguard_policy:
        kwargs["safeguard_policy"] = safeguard_policy

    try:
        async for event in a_run_group_chat_iter(**kwargs):
            # AG2's @wrap_event produces a two-layer structure:
            #   event.type    — event type string
            #   event.content — inner event with actual payload data
            inner = getattr(event, "content", None)

            if isinstance(event, TextEvent) and on_text:
                text = getattr(inner, "content", "") if inner is not None else ""
                sender = getattr(inner, "sender", "unknown") if inner is not None else "unknown"
                await _maybe_await(on_text, text, sender)
            elif isinstance(event, ToolCallEvent) and on_tool_use:
                tool_calls = getattr(inner, "tool_calls", []) if inner is not None else []
                first = tool_calls[0] if tool_calls else None
                tool_name = getattr(getattr(first, "function", None), "name", "") if first else ""
                tool_args = (
                    getattr(getattr(first, "function", None), "arguments", None) if first else None
                )
                sender = getattr(inner, "sender", "unknown") if inner is not None else "unknown"
                await _maybe_await(on_tool_use, tool_name, sender, tool_args)
            elif isinstance(event, ToolResponseEvent) and on_tool_result:
                tool_responses = getattr(inner, "tool_responses", []) if inner is not None else []
                first = tool_responses[0] if tool_responses else None
                tool_output = getattr(first, "content", None) if first else None
                sender = getattr(inner, "sender", "unknown") if inner is not None else "unknown"
                await _maybe_await(on_tool_result, sender, tool_output)
            elif isinstance(event, GroupChatRunChatEvent) and on_speaker:
                speaker = getattr(inner, "speaker", "unknown") if inner is not None else "unknown"
                await _maybe_await(on_speaker, speaker)
            elif isinstance(event, SelectSpeakerEvent) and on_speaker:
                agents = getattr(inner, "agents", []) if inner is not None else []
                first_name = getattr(agents[0], "name", str(agents[0])) if agents else "unknown"
                await _maybe_await(on_speaker, first_name)
            yield event
    except Exception:
        logger.exception("AG2 GroupChat streaming failed")
        raise

    if on_complete:
        await _maybe_await(on_complete, None)


async def _maybe_await(fn: Callable, *args: Any) -> Any:
    from lionagi.ln.concurrency.utils import is_coro_func

    # Check fn BEFORE calling it. Checking the result (a coroutine object)
    # with is_coro_func() would always return False — coroutine objects are
    # not coroutine functions.
    if is_coro_func(fn):
        return await fn(*args)
    return fn(*args)
